In [37]:
import numpy as np
import pandas as pd

In [189]:
#create array 
# a = np.array([]) 1d array 
# a = np.array([],[]) 2d array 
# a = np.arrat([],[],[]) 3d array

#b = np.one(5)  # print 5 times 1 in bydefault float
#b = np.ones((5,6), dtype= int) # print 6 times 1 & 5 rows

#c = np.zeros(5)  #print 5 times 1 in bydefault float
#c = np.zeros((5,6)) #print 6 times 1 & 5 rows

#############################################
a = np.arange(start,end,step)
a = np.arange(1,10) # print 1 to 10
a = np.arange(1,10,2) # print 1 to 10 by 2 steps 


In [191]:
# .ndim   shows 2d/1d/3d diamension
# .shape  rows and colums show
# .dtype  data type show int/float
# .size   total numbers in tables 
# type()
# .ravel() convert muktidiamentional array to 1d 
# .flatten()  convert muktidiamentional array to 1d
# .transpose() row convert into column


############################################
.reshape(2,6) #convert 2d array so 2 and 12 values/2 = 6 
.reshape(3,4) #convert 3d array so 3 and 12 values/3 = 4
######################################################3
np.std() # standerd deviatation
np.sum()
np.mean()
np.sqrt()
np.concat((),axis = 1) #conacat
np.vstack() # vertical concatinantion
np.hstack() # horizontal concatinat
np.split(a,2,axis=1) 
np.exp() # each element exponenet
np.log()
a[1:3] slicing
np.sin(180), np.cos(90)
####################################################


In [193]:
print("Hi")

Hi


In [195]:
import numpy as np
arr_1d = np.array([11,34,4,4,4,4,4])

In [197]:
print(arr_1d)

[11 34  4  4  4  4  4]


In [285]:

print(arr_1d.ndim)
print(arr_1d.shape)
print(type(arr_1d))

1
(7,)
<class 'numpy.ndarray'>


In [293]:
arr_2d = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [301]:
print(arr_2d.ndim)
print(arr_2d.shape)
print(type(arr_2d))
print(arr_2d.dtype)

2
(2, 6)
<class 'numpy.ndarray'>
int32


In [279]:
print(arr_2d.size)
print(arr_2d.ndim)
print(arr_2d.shape)

12
2
(2, 6)


In [219]:
arr_3d = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [221]:
print(arr_3d)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [275]:
print(f"diam of array: {arr_3d.ndim}")
print(f"size of array:{arr_3d.size}")
print(f"shape of array:{arr_3d.shape}")


diam of array: 2
size of array:15
shape of array:(3, 5)


In [261]:
x = np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [257]:
y = np.ones((6,8),dtype = int)
y

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [255]:
z = np.zeros((7,9), dtype = int)
z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [253]:
array_1d = np.arange(1,13)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [339]:
array_1d = np.arange(1,13)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [331]:
# 1d array convert into multidiamentional array
array_1d.reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [341]:
array_1d.reshape(2,6) # convert 2d array so 2 and 12 values/2 = 6 

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [349]:
array_1d.reshape(3,4) # convert 3d array so 3 and 12 values/3 = 4 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [345]:
13/3

4.333333333333333

In [375]:
array_1d.linespace(1,5,4)

AttributeError: 'numpy.ndarray' object has no attribute 'linespace'

In [357]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [391]:
ar = np.arange(1,13).reshape(2,6)
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [393]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [397]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [399]:
ar.max()

12

In [401]:
import numpy as np

In [403]:
mx = np.arange(1,101).reshape(10,10)

In [405]:
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [407]:
mx[0,0]

1

In [415]:
mx[0,0].ndim

0

In [409]:
mx[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [417]:
mx[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [419]:
mx[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [421]:
mx[:,0:1].ndim

2

In [431]:
mx[1:4,4:8]

array([[15, 16, 17, 18],
       [25, 26, 27, 28],
       [35, 36, 37, 38]])

In [427]:
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [433]:
mx[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [445]:
a = np.arange(17,33).reshape(4,4)

In [447]:
a

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [471]:
b = np.arange(9,41).reshape(4,4)

ValueError: cannot reshape array of size 32 into shape (4,4)

In [463]:
30/4

7.5

In [487]:
pip install xlrd

   ---------------------------------------- 0.0/96.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/96.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/96.5 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/96.5 kB ? eta -:--:--
   ---------------- ----------------------- 41.0/96.5 kB 393.8 kB/s eta 0:00:01
   ---------------------------------------- 96.5/96.5 kB 690.3 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [29]:
import pandas as pd

In [31]:
df = pd.read_excel("D://overall_practice_Files//c4c_data//practice_files_for_ml//Myshift _11am.xlsx")

In [32]:
df

Myshift  Unnamed: 1         Unnamed: 2  \
0     S.No         NaN         Ref Number   
1        1         NaN  TSK101446898        
2        2         NaN  TSK101484572        
3        3         NaN  TSK101489204        
4        4         NaN  TSK101489244        
5        5         NaN  TSK101489766        
6        6         NaN  TSK101495994        
7        7         NaN  TSK101500370        
8        8         NaN  TSK101502620        
9        9         NaN  TSK101503822        
10      10         NaN  TSK101505384        
11      11         NaN  TSK101507898        
12      12         NaN  TSK101513391        
13      13         NaN  TSK101513621        
14      14         NaN  TSK101514102        
15      15         NaN  TSK101522037        
16      16         NaN  TSK101526681        
17      17         NaN  TSK101526899        
18      18         NaN  TSK101527067        
19      19         NaN  TSK101527445        
20      20         NaN  TSK101528089        
21      21         NaN  TSK101528147        
22      22         NaN  TSK101528923        
23      23         NaN  TSK101529251        
24      24         NaN  TSK101529415        
25      25         NaN  TSK101531511        
26      26         NaN  TSK101531567        
27      27         NaN  TSK101531629        

                                           Unnamed: 3           Unnamed: 4  \
0                                         Description                Owner   
1                check with chaitanya mam new develop      Prakash Hannure   
2                                 check with dashrath     Rachel Prassanna   
3                            pending in rajesh / asif      Priyanka  Gadde   
4                          have to check with kailash      Priyanka  Gadde   
5                                       chaitanya mam      Priyanka  Gadde   
6            checked with rajesh inform to reach john     Rachel Prassanna   
7                                 pending on customer     Rachel Prassanna   
8                                     pending on user      Prakash Hannure   
9                                        user confirm        Ruchika Yadav   
10                    pending for user remote session     Rachel Prassanna   
11                      have to check with suresh sir     Rachel Prassanna   
12                                      chaitanya mam      Prakash Hannure   
13                         have to check with kailash      Prakash Hannure   
14                            have to check with john     Rachel Prassanna   
15                                   pending at user       Prakash Hannure   
16                                   pending at user     Hrushitosh Ingole   
17                                   pending at user         Ruchika Yadav   
18  have to check with john/roster  & on round robbin  Narsimhareddy Akiti   
19                                    pending on user      Bhargavi Korada   
20                               working on it  Akiti  Narsimhareddy Akiti   
21                                    pending on user     Rachel Prassanna   
22  need to check with john / kailash -- rachel re...      Bhargavi Korada   
23                         have to check with kailash        Ruchika Yadav   
24                             working on it (Rachel)     Rachel Prassanna   
25                                 checking with john     Mallari  Hemanth   
26                                     from SAM Team      Rachel Prassanna   
27                                    pending on user     Rachel Prassanna   

             Unnamed: 5                                         Unnamed: 6  \
0                Status                                            Subject   
1              Activity                                 Tickets Assignment   
2              Activity  Server Stopped State in CMDB: UPG-23-C26203 - ...   
3              Activity                           ACM Details Confirmation   
4              Activity                     

In [501]:
df.shape

(28, 12)

In [503]:
df.describe

<bound method NDFrame.describe of    Myshift  Unnamed: 1         Unnamed: 2  \
0     S.No         NaN         Ref Number   
1        1         NaN  TSK101446898        
2        2         NaN  TSK101484572        
3        3         NaN  TSK101489204        
4        4         NaN  TSK101489244        
5        5         NaN  TSK101489766        
6        6         NaN  TSK101495994        
7        7         NaN  TSK101500370        
8        8         NaN  TSK101502620        
9        9         NaN  TSK101503822        
10      10         NaN  TSK101505384        
11      11         NaN  TSK101507898        
12      12         NaN  TSK101513391        
13      13         NaN  TSK101513621        
14      14         NaN  TSK101514102        
15      15         NaN  TSK101522037        
16      16         NaN  TSK101526681        
17      17         NaN  TSK101526899        
18      18         NaN  TSK101527067        
19      19         NaN  TSK101527445        
20      20         Na

In [505]:
df.head()

Myshift  Unnamed: 1         Unnamed: 2  \
0    S.No         NaN         Ref Number   
1       1         NaN  TSK101446898        
2       2         NaN  TSK101484572        
3       3         NaN  TSK101489204        
4       4         NaN  TSK101489244        

                             Unnamed: 3        Unnamed: 4 Unnamed: 5  \
0                           Description             Owner     Status   
1  check with chaitanya mam new develop   Prakash Hannure   Activity   
2                   check with dashrath  Rachel Prassanna   Activity   
3              pending in rajesh / asif   Priyanka  Gadde   Activity   
4            have to check with kailash   Priyanka  Gadde   Activity   

                                          Unnamed: 6  \
0                                            Subject   
1                                 Tickets Assignment   
2  Server Stopped State in CMDB: UPG-23-C26203 - ...   
3                           ACM Details Confirmation   
4                           Asego Technologies LLP -   

                         Unnamed: 7        Unnamed: 8           Unnamed: 9  \
0                          Org Name      Last Replier         Created Date   
1  CLOUD4C SERVICES PRIVATE LIMITED   Prakash Hannure  2023-07-04 13:26:27   
2  CLOUD4C SERVICES PRIVATE LIMITED  Rachel Prassanna  2023-07-12 02:24:03   
3          Ctrls Datacenter Pvt Ltd               NaN  2023-07-13 16:35:27   
4  CLOUD4C SERVICES PRIVATE LIMITED   Prakash Hannure  2023-07-13 16:35:47   

     Unnamed: 10 Unnamed: 11  
0  Last Activity  Operations  
1   0 d 10 h 39m         NaN  
2   0 d 17 h 24m         NaN  
3     0 d 0 h 0m         NaN  
4     0 d 0 h 0m         NaN

In [534]:
df.iloc[[3,7,],2:6]

Unnamed: 2                Unnamed: 3        Unnamed: 4 Unnamed: 5
3  TSK101489204       pending in rajesh / asif   Priyanka  Gadde   Activity
7  TSK101500370            pending on customer  Rachel Prassanna   Activity

In [531]:
df.iloc[[2,5,], 2:5]

Unnamed: 2           Unnamed: 3        Unnamed: 4
2  TSK101484572       check with dashrath  Rachel Prassanna
5  TSK101489766             chaitanya mam   Priyanka  Gadde

In [5]:
def sqr(b):
    yield b*b
c = sqr(6)
next(c)

36

In [23]:
def gen(b):
    while b>20:
        yield b
        b=b-1
    
c = gen(55)
c.__next__()


55

In [15]:
def gen(b):
    while b > 20:
        yield b
        b = b - 1

# Create a generator object with an initial value greater than 20
c = gen(25)

# Print all values from the generator
for value in c:
    print(value)


25
24
23
22
21


In [23]:
a = np.array([[1,2,3,3,4,4],[1,2,3,4,5,6]])

In [25]:
import numpy as np

In [27]:
print(a)

[[1 2 3 3 4 4]
 [1 2 3 4 5 6]]


In [37]:
df.shape

(28, 12)

In [47]:
df.iloc([1:2])

SyntaxError: invalid syntax (4132967355.py, line 1)

In [59]:
df

Myshift  Unnamed: 1         Unnamed: 2  \
0     S.No         NaN         Ref Number   
1        1         NaN  TSK101446898        
2        2         NaN  TSK101484572        
3        3         NaN  TSK101489204        
4        4         NaN  TSK101489244        
5        5         NaN  TSK101489766        
6        6         NaN  TSK101495994        
7        7         NaN  TSK101500370        
8        8         NaN  TSK101502620        
9        9         NaN  TSK101503822        
10      10         NaN  TSK101505384        
11      11         NaN  TSK101507898        
12      12         NaN  TSK101513391        
13      13         NaN  TSK101513621        
14      14         NaN  TSK101514102        
15      15         NaN  TSK101522037        
16      16         NaN  TSK101526681        
17      17         NaN  TSK101526899        
18      18         NaN  TSK101527067        
19      19         NaN  TSK101527445        
20      20         NaN  TSK101528089        
21      21         NaN  TSK101528147        
22      22         NaN  TSK101528923        
23      23         NaN  TSK101529251        
24      24         NaN  TSK101529415        
25      25         NaN  TSK101531511        
26      26         NaN  TSK101531567        
27      27         NaN  TSK101531629        

                                           Unnamed: 3           Unnamed: 4  \
0                                         Description                Owner   
1                check with chaitanya mam new develop      Prakash Hannure   
2                                 check with dashrath     Rachel Prassanna   
3                            pending in rajesh / asif      Priyanka  Gadde   
4                          have to check with kailash      Priyanka  Gadde   
5                                       chaitanya mam      Priyanka  Gadde   
6            checked with rajesh inform to reach john     Rachel Prassanna   
7                                 pending on customer     Rachel Prassanna   
8                                     pending on user      Prakash Hannure   
9                                        user confirm        Ruchika Yadav   
10                    pending for user remote session     Rachel Prassanna   
11                      have to check with suresh sir     Rachel Prassanna   
12                                      chaitanya mam      Prakash Hannure   
13                         have to check with kailash      Prakash Hannure   
14                            have to check with john     Rachel Prassanna   
15                                   pending at user       Prakash Hannure   
16                                   pending at user     Hrushitosh Ingole   
17                                   pending at user         Ruchika Yadav   
18  have to check with john/roster  & on round robbin  Narsimhareddy Akiti   
19                                    pending on user      Bhargavi Korada   
20                               working on it  Akiti  Narsimhareddy Akiti   
21                                    pending on user     Rachel Prassanna   
22  need to check with john / kailash -- rachel re...      Bhargavi Korada   
23                         have to check with kailash        Ruchika Yadav   
24                             working on it (Rachel)     Rachel Prassanna   
25                                 checking with john     Mallari  Hemanth   
26                                     from SAM Team      Rachel Prassanna   
27                                    pending on user     Rachel Prassanna   

             Unnamed: 5                                         Unnamed: 6  \
0                Status                                            Subject   
1              Activity                                 Tickets Assignment   
2              Activity  Server Stopped State in CMDB: UPG-23-C26203 - ...   
3              Activity                           ACM Details Confirmation   
4              Activity                     

In [81]:
df.rename(columns = {'Unnamed:1': 'first'}]

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (2319640889.py, line 1)

In [101]:
df = df.rename(columns={'X': 'a', 'Y': 'b', 'Unnamed: 3': 'c', 'Unnamed: 4': 'd','Unnamed: 4': 'd','Unnamed: 5': 'e','Unnamed: 6': 'f','Unnamed: 7': 'g','Unnamed: 8': 'h','Unnamed: 9': 'i','Unnamed: 9': 'j','Unnamed: 10': 'k','Unnamed: 11': 'l',})

In [103]:
df

Myshift   a                  b  \
0     S.No NaN         Ref Number   
1        1 NaN  TSK101446898        
2        2 NaN  TSK101484572        
3        3 NaN  TSK101489204        
4        4 NaN  TSK101489244        
5        5 NaN  TSK101489766        
6        6 NaN  TSK101495994        
7        7 NaN  TSK101500370        
8        8 NaN  TSK101502620        
9        9 NaN  TSK101503822        
10      10 NaN  TSK101505384        
11      11 NaN  TSK101507898        
12      12 NaN  TSK101513391        
13      13 NaN  TSK101513621        
14      14 NaN  TSK101514102        
15      15 NaN  TSK101522037        
16      16 NaN  TSK101526681        
17      17 NaN  TSK101526899        
18      18 NaN  TSK101527067        
19      19 NaN  TSK101527445        
20      20 NaN  TSK101528089        
21      21 NaN  TSK101528147        
22      22 NaN  TSK101528923        
23      23 NaN  TSK101529251        
24      24 NaN  TSK101529415        
25      25 NaN  TSK101531511        
26      26 NaN  TSK101531567        
27      27 NaN  TSK101531629        

                                                    c                    d  \
0                                         Description                Owner   
1                check with chaitanya mam new develop      Prakash Hannure   
2                                 check with dashrath     Rachel Prassanna   
3                            pending in rajesh / asif      Priyanka  Gadde   
4                          have to check with kailash      Priyanka  Gadde   
5                                       chaitanya mam      Priyanka  Gadde   
6            checked with rajesh inform to reach john     Rachel Prassanna   
7                                 pending on customer     Rachel Prassanna   
8                                     pending on user      Prakash Hannure   
9                                        user confirm        Ruchika Yadav   
10                    pending for user remote session     Rachel Prassanna   
11                      have to check with suresh sir     Rachel Prassanna   
12                                      chaitanya mam      Prakash Hannure   
13                         have to check with kailash      Prakash Hannure   
14                            have to check with john     Rachel Prassanna   
15                                   pending at user       Prakash Hannure   
16                                   pending at user     Hrushitosh Ingole   
17                                   pending at user         Ruchika Yadav   
18  have to check with john/roster  & on round robbin  Narsimhareddy Akiti   
19                                    pending on user      Bhargavi Korada   
20                               working on it  Akiti  Narsimhareddy Akiti   
21                                    pending on user     Rachel Prassanna   
22  need to check with john / kailash -- rachel re...      Bhargavi Korada   
23                         have to check with kailash        Ruchika Yadav   
24                             working on it (Rachel)     Rachel Prassanna   
25                                 checking with john     Mallari  Hemanth   
26                                     from SAM Team      Rachel Prassanna   
27                                    pending on user     Rachel Prassanna   

                      e                                                  e  \
0                Status                                            Subject   
1              Activity                                 Tickets Assignment   
2              Activity  Server Stopped State in CMDB: UPG-23-C26203 - ...   
3              Activity                           ACM Details Confirmation   
4              Activity                           Asego Technologies LLP -   
5              Activity             regarding the wrongly assigned tickets   
6              Activity  Same Ticket assigning for different Organizati...   
7              Activity  Signoff document 

In [171]:
df.isnull().sum(axis =1)

0     1
1     2
2     2
3     3
4     2
5     3
6     2
7     3
8     2
9     3
10    3
11    3
12    2
13    2
14    3
15    2
16    2
17    2
18    2
19    3
20    3
21    3
22    2
23    3
24    3
25    2
26    2
27    2
dtype: int64

In [127]:
df.fillna(0),inplace == True

NameError: name 'inplace' is not defined

In [123]:
df.isnull().sum()

Myshift     0
a          28
b           0
c           0
d           0
e           0
e           0
f           0
g          12
i           0
j           0
k          27
dtype: int64

In [145]:
df.head(3)

Myshift   a                  b                                     c  \
0    S.No NaN         Ref Number                           Description   
1       1 NaN  TSK101446898       check with chaitanya mam new develop   
2       2 NaN  TSK101484572                        check with dashrath   

                  d         e  \
0             Owner    Status   
1   Prakash Hannure  Activity   
2  Rachel Prassanna  Activity   

                                                   e  \
0                                            Subject   
1                                 Tickets Assignment   
2  Server Stopped State in CMDB: UPG-23-C26203 - ...   

                                  f                 g                    i  \
0                          Org Name      Last Replier         Created Date   
1  CLOUD4C SERVICES PRIVATE LIMITED   Prakash Hannure  2023-07-04 13:26:27   
2  CLOUD4C SERVICES PRIVATE LIMITED  Rachel Prassanna  2023-07-12 02:24:03   

               j           k  
0  Last Activity  Operations  
1   0 d 10 h 39m         NaN  
2   0 d 17 h 24m         NaN

In [149]:
df.tail(1)

Myshift   a                  b                c                 d  \
27      27 NaN  TSK101531629       pending on user  Rachel Prassanna   

                      e                                              e  \
27  Pending On Customer  unable to change the component --  0000624854   

                           f                 g                    i  \
27  Ctrls Datacenter Pvt Ltd  Rachel Prassanna  2023-07-26 06:12:26   

             j    k  
27  0 d 0 h 9m  NaN

In [157]:
print(df.shape[0])
print(df.shape[1])

28
12


In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Myshift  28 non-null     object 
 1   a        0 non-null      float64
 2   b        28 non-null     object 
 3   c        28 non-null     object 
 4   d        28 non-null     object 
 5   e        28 non-null     object 
 6   e        28 non-null     object 
 7   f        28 non-null     object 
 8   g        16 non-null     object 
 9   i        28 non-null     object 
 10  j        28 non-null     object 
 11  k        1 non-null      object 
dtypes: float64(1), object(11)
memory usage: 2.8+ KB


In [173]:
df.head(10)['b']

0           Ref Number
1    TSK101446898     
2    TSK101484572     
3    TSK101489204     
4    TSK101489244     
5    TSK101489766     
6    TSK101495994     
7    TSK101500370     
8    TSK101502620     
9    TSK101503822     
Name: b, dtype: object

In [ ]:
df['j'].mean()

In [177]:
df.columns

Index(['Myshift', 'a', 'b', 'c', 'd', 'e', 'e', 'f', 'g', 'i', 'j', 'k'], dtype='object')

In [179]:
df

Myshift   a                  b  \
0     S.No NaN         Ref Number   
1        1 NaN  TSK101446898        
2        2 NaN  TSK101484572        
3        3 NaN  TSK101489204        
4        4 NaN  TSK101489244        
5        5 NaN  TSK101489766        
6        6 NaN  TSK101495994        
7        7 NaN  TSK101500370        
8        8 NaN  TSK101502620        
9        9 NaN  TSK101503822        
10      10 NaN  TSK101505384        
11      11 NaN  TSK101507898        
12      12 NaN  TSK101513391        
13      13 NaN  TSK101513621        
14      14 NaN  TSK101514102        
15      15 NaN  TSK101522037        
16      16 NaN  TSK101526681        
17      17 NaN  TSK101526899        
18      18 NaN  TSK101527067        
19      19 NaN  TSK101527445        
20      20 NaN  TSK101528089        
21      21 NaN  TSK101528147        
22      22 NaN  TSK101528923        
23      23 NaN  TSK101529251        
24      24 NaN  TSK101529415        
25      25 NaN  TSK101531511        
26      26 NaN  TSK101531567        
27      27 NaN  TSK101531629        

                                                    c                    d  \
0                                         Description                Owner   
1                check with chaitanya mam new develop      Prakash Hannure   
2                                 check with dashrath     Rachel Prassanna   
3                            pending in rajesh / asif      Priyanka  Gadde   
4                          have to check with kailash      Priyanka  Gadde   
5                                       chaitanya mam      Priyanka  Gadde   
6            checked with rajesh inform to reach john     Rachel Prassanna   
7                                 pending on customer     Rachel Prassanna   
8                                     pending on user      Prakash Hannure   
9                                        user confirm        Ruchika Yadav   
10                    pending for user remote session     Rachel Prassanna   
11                      have to check with suresh sir     Rachel Prassanna   
12                                      chaitanya mam      Prakash Hannure   
13                         have to check with kailash      Prakash Hannure   
14                            have to check with john     Rachel Prassanna   
15                                   pending at user       Prakash Hannure   
16                                   pending at user     Hrushitosh Ingole   
17                                   pending at user         Ruchika Yadav   
18  have to check with john/roster  & on round robbin  Narsimhareddy Akiti   
19                                    pending on user      Bhargavi Korada   
20                               working on it  Akiti  Narsimhareddy Akiti   
21                                    pending on user     Rachel Prassanna   
22  need to check with john / kailash -- rachel re...      Bhargavi Korada   
23                         have to check with kailash        Ruchika Yadav   
24                             working on it (Rachel)     Rachel Prassanna   
25                                 checking with john     Mallari  Hemanth   
26                                     from SAM Team      Rachel Prassanna   
27                                    pending on user     Rachel Prassanna   

                      e                                                  e  \
0                Status                                            Subject   
1              Activity                                 Tickets Assignment   
2              Activity  Server Stopped State in CMDB: UPG-23-C26203 - ...   
3              Activity                           ACM Details Confirmation   
4              Activity                           Asego Technologies LLP -   
5              Activity             regarding the wrongly assigned tickets   
6              Activity  Same Ticket assigning for different Organizati...   
7              Activity  Signoff document 

In [199]:
df[df['d'] == 'Rachel Prassanna'].count()

Myshift    10
a           0
b          10
c          10
d          10
e          10
e          10
f          10
g           4
i          10
j          10
k           0
dtype: int64

In [205]:
df[df['d'].str.contains('Rachel Prassanna')]

Myshift   a                  b                                         c  \
2        2 NaN  TSK101484572                            check with dashrath   
6        6 NaN  TSK101495994       checked with rajesh inform to reach john   
7        7 NaN  TSK101500370                            pending on customer   
10      10 NaN  TSK101505384                pending for user remote session   
11      11 NaN  TSK101507898                  have to check with suresh sir   
14      14 NaN  TSK101514102                        have to check with john   
21      21 NaN  TSK101528147                                pending on user   
24      24 NaN  TSK101529415                         working on it (Rachel)   
26      26 NaN  TSK101531567                                 from SAM Team    
27      27 NaN  TSK101531629                                pending on user   

                   d                    e  \
2   Rachel Prassanna             Activity   
6   Rachel Prassanna             Activity   
7   Rachel Prassanna             Activity   
10  Rachel Prassanna             Activity   
11  Rachel Prassanna             Activity   
14  Rachel Prassanna             Activity   
21  Rachel Prassanna  Pending On Customer   
24  Rachel Prassanna             Activity   
26  Rachel Prassanna             Activity   
27  Rachel Prassanna  Pending On Customer   

                                                    e  \
2   Server Stopped State in CMDB: UPG-23-C26203 - ...   
6   Same Ticket assigning for different Organizati...   
7   Signoff document unable to download  -- MUM-En...   
10                    Action items on automation team   
11       ExxonMobil: Mumbai Colo Portal Access Review   
14                      unable to approve the tickets   
21          Admin center not able to download reports   
24                         Unable to find worklog tab   
26                          My Shift attachment issue   
27      unable to change the component --  0000624854   

                                      f                 g  \
2      CLOUD4C SERVICES PRIVATE LIMITED  Rachel Prassanna   
6   VIVA COMMUNICATIONS PRIVATE LIMITED  Rachel Prassanna   
7              Ctrls Datacenter Pvt Ltd               NaN   
10     CLOUD4C SERVICES PRIVATE LIMITED               NaN   
11             Ctrls Datacenter Pvt Ltd               NaN   
14  VIVA COMMUNICATIONS PRIVATE LIMITED               NaN   
21             Ctrls Datacenter Pvt Ltd               NaN   
24             Ctrls Datacenter Pvt Ltd               NaN   
26         Cloud4c Services Pvt Limited   Prakash Hannure   
27             Ctrls Datacenter Pvt Ltd  Rachel Prassanna   

                      i             j    k  
2   2023-07-12 02:24:03  0 d 17 h 24m  NaN  
6   2023-07-14 19:58:52  4 d 16 h 46m  NaN  
7   2023-07-17 15:24:02  6 d 18 h 44m  NaN  
10  2023-07-18 17:11:59    7 d 3 h 1m  NaN  
11  2023-07-19 17:17:40  4 d 16 h 43m  NaN  
14  2023-07-21 13:56:41  0 d 10 h 32m  NaN  
21  2023-07-25 13:57:54   0 d 11 h 9m  NaN  
24  2023-07-25 17:01:35   0 d 9 h 58m  NaN  
26  2023-07-26 05:14:33   0 d 1 h 57m  NaN  
27  2023-07-26 06:12:26    0 d 0 h 9m  NaN

In [207]:
df[df['d'].str.contains('Rachel Prassanna')] # d contains 'Rachel' jithe jithe rachel ahe te dakhwel

Myshift   a                  b                                         c  \
2        2 NaN  TSK101484572                            check with dashrath   
6        6 NaN  TSK101495994       checked with rajesh inform to reach john   
7        7 NaN  TSK101500370                            pending on customer   
10      10 NaN  TSK101505384                pending for user remote session   
11      11 NaN  TSK101507898                  have to check with suresh sir   
14      14 NaN  TSK101514102                        have to check with john   
21      21 NaN  TSK101528147                                pending on user   
24      24 NaN  TSK101529415                         working on it (Rachel)   
26      26 NaN  TSK101531567                                 from SAM Team    
27      27 NaN  TSK101531629                                pending on user   

                   d                    e  \
2   Rachel Prassanna             Activity   
6   Rachel Prassanna             Activity   
7   Rachel Prassanna             Activity   
10  Rachel Prassanna             Activity   
11  Rachel Prassanna             Activity   
14  Rachel Prassanna             Activity   
21  Rachel Prassanna  Pending On Customer   
24  Rachel Prassanna             Activity   
26  Rachel Prassanna             Activity   
27  Rachel Prassanna  Pending On Customer   

                                                    e  \
2   Server Stopped State in CMDB: UPG-23-C26203 - ...   
6   Same Ticket assigning for different Organizati...   
7   Signoff document unable to download  -- MUM-En...   
10                    Action items on automation team   
11       ExxonMobil: Mumbai Colo Portal Access Review   
14                      unable to approve the tickets   
21          Admin center not able to download reports   
24                         Unable to find worklog tab   
26                          My Shift attachment issue   
27      unable to change the component --  0000624854   

                                      f                 g  \
2      CLOUD4C SERVICES PRIVATE LIMITED  Rachel Prassanna   
6   VIVA COMMUNICATIONS PRIVATE LIMITED  Rachel Prassanna   
7              Ctrls Datacenter Pvt Ltd               NaN   
10     CLOUD4C SERVICES PRIVATE LIMITED               NaN   
11             Ctrls Datacenter Pvt Ltd               NaN   
14  VIVA COMMUNICATIONS PRIVATE LIMITED               NaN   
21             Ctrls Datacenter Pvt Ltd               NaN   
24             Ctrls Datacenter Pvt Ltd               NaN   
26         Cloud4c Services Pvt Limited   Prakash Hannure   
27             Ctrls Datacenter Pvt Ltd  Rachel Prassanna   

                      i             j    k  
2   2023-07-12 02:24:03  0 d 17 h 24m  NaN  
6   2023-07-14 19:58:52  4 d 16 h 46m  NaN  
7   2023-07-17 15:24:02  6 d 18 h 44m  NaN  
10  2023-07-18 17:11:59    7 d 3 h 1m  NaN  
11  2023-07-19 17:17:40  4 d 16 h 43m  NaN  
14  2023-07-21 13:56:41  0 d 10 h 32m  NaN  
21  2023-07-25 13:57:54   0 d 11 h 9m  NaN  
24  2023-07-25 17:01:35   0 d 9 h 58m  NaN  
26  2023-07-26 05:14:33   0 d 1 h 57m  NaN  
27  2023-07-26 06:12:26    0 d 0 h 9m  NaN

In [209]:
df[df['d'].str.contains('Rachel Prassanna', case = False)] # d contains 'Rachel' jithe jithe rachel ahe te dakhwel

Myshift   a                  b                                         c  \
2        2 NaN  TSK101484572                            check with dashrath   
6        6 NaN  TSK101495994       checked with rajesh inform to reach john   
7        7 NaN  TSK101500370                            pending on customer   
10      10 NaN  TSK101505384                pending for user remote session   
11      11 NaN  TSK101507898                  have to check with suresh sir   
14      14 NaN  TSK101514102                        have to check with john   
21      21 NaN  TSK101528147                                pending on user   
24      24 NaN  TSK101529415                         working on it (Rachel)   
26      26 NaN  TSK101531567                                 from SAM Team    
27      27 NaN  TSK101531629                                pending on user   

                   d                    e  \
2   Rachel Prassanna             Activity   
6   Rachel Prassanna             Activity   
7   Rachel Prassanna             Activity   
10  Rachel Prassanna             Activity   
11  Rachel Prassanna             Activity   
14  Rachel Prassanna             Activity   
21  Rachel Prassanna  Pending On Customer   
24  Rachel Prassanna             Activity   
26  Rachel Prassanna             Activity   
27  Rachel Prassanna  Pending On Customer   

                                                    e  \
2   Server Stopped State in CMDB: UPG-23-C26203 - ...   
6   Same Ticket assigning for different Organizati...   
7   Signoff document unable to download  -- MUM-En...   
10                    Action items on automation team   
11       ExxonMobil: Mumbai Colo Portal Access Review   
14                      unable to approve the tickets   
21          Admin center not able to download reports   
24                         Unable to find worklog tab   
26                          My Shift attachment issue   
27      unable to change the component --  0000624854   

                                      f                 g  \
2      CLOUD4C SERVICES PRIVATE LIMITED  Rachel Prassanna   
6   VIVA COMMUNICATIONS PRIVATE LIMITED  Rachel Prassanna   
7              Ctrls Datacenter Pvt Ltd               NaN   
10     CLOUD4C SERVICES PRIVATE LIMITED               NaN   
11             Ctrls Datacenter Pvt Ltd               NaN   
14  VIVA COMMUNICATIONS PRIVATE LIMITED               NaN   
21             Ctrls Datacenter Pvt Ltd               NaN   
24             Ctrls Datacenter Pvt Ltd               NaN   
26         Cloud4c Services Pvt Limited   Prakash Hannure   
27             Ctrls Datacenter Pvt Ltd  Rachel Prassanna   

                      i             j    k  
2   2023-07-12 02:24:03  0 d 17 h 24m  NaN  
6   2023-07-14 19:58:52  4 d 16 h 46m  NaN  
7   2023-07-17 15:24:02  6 d 18 h 44m  NaN  
10  2023-07-18 17:11:59    7 d 3 h 1m  NaN  
11  2023-07-19 17:17:40  4 d 16 h 43m  NaN  
14  2023-07-21 13:56:41  0 d 10 h 32m  NaN  
21  2023-07-25 13:57:54   0 d 11 h 9m  NaN  
24  2023-07-25 17:01:35   0 d 9 h 58m  NaN  
26  2023-07-26 05:14:33   0 d 1 h 57m  NaN  
27  2023-07-26 06:12:26    0 d 0 h 9m  NaN

In [221]:
df[df['d'] == 'Rachel Prassanna'] # find the name of the Rachel in d column

Myshift   a                  b                                         c  \
2        2 NaN  TSK101484572                            check with dashrath   
6        6 NaN  TSK101495994       checked with rajesh inform to reach john   
7        7 NaN  TSK101500370                            pending on customer   
10      10 NaN  TSK101505384                pending for user remote session   
11      11 NaN  TSK101507898                  have to check with suresh sir   
14      14 NaN  TSK101514102                        have to check with john   
21      21 NaN  TSK101528147                                pending on user   
24      24 NaN  TSK101529415                         working on it (Rachel)   
26      26 NaN  TSK101531567                                 from SAM Team    
27      27 NaN  TSK101531629                                pending on user   

                   d                    e  \
2   Rachel Prassanna             Activity   
6   Rachel Prassanna             Activity   
7   Rachel Prassanna             Activity   
10  Rachel Prassanna             Activity   
11  Rachel Prassanna             Activity   
14  Rachel Prassanna             Activity   
21  Rachel Prassanna  Pending On Customer   
24  Rachel Prassanna             Activity   
26  Rachel Prassanna             Activity   
27  Rachel Prassanna  Pending On Customer   

                                                    e  \
2   Server Stopped State in CMDB: UPG-23-C26203 - ...   
6   Same Ticket assigning for different Organizati...   
7   Signoff document unable to download  -- MUM-En...   
10                    Action items on automation team   
11       ExxonMobil: Mumbai Colo Portal Access Review   
14                      unable to approve the tickets   
21          Admin center not able to download reports   
24                         Unable to find worklog tab   
26                          My Shift attachment issue   
27      unable to change the component --  0000624854   

                                      f                 g  \
2      CLOUD4C SERVICES PRIVATE LIMITED  Rachel Prassanna   
6   VIVA COMMUNICATIONS PRIVATE LIMITED  Rachel Prassanna   
7              Ctrls Datacenter Pvt Ltd               NaN   
10     CLOUD4C SERVICES PRIVATE LIMITED               NaN   
11             Ctrls Datacenter Pvt Ltd               NaN   
14  VIVA COMMUNICATIONS PRIVATE LIMITED               NaN   
21             Ctrls Datacenter Pvt Ltd               NaN   
24             Ctrls Datacenter Pvt Ltd               NaN   
26         Cloud4c Services Pvt Limited   Prakash Hannure   
27             Ctrls Datacenter Pvt Ltd  Rachel Prassanna   

                      i             j    k  
2   2023-07-12 02:24:03  0 d 17 h 24m  NaN  
6   2023-07-14 19:58:52  4 d 16 h 46m  NaN  
7   2023-07-17 15:24:02  6 d 18 h 44m  NaN  
10  2023-07-18 17:11:59    7 d 3 h 1m  NaN  
11  2023-07-19 17:17:40  4 d 16 h 43m  NaN  
14  2023-07-21 13:56:41  0 d 10 h 32m  NaN  
21  2023-07-25 13:57:54   0 d 11 h 9m  NaN  
24  2023-07-25 17:01:35   0 d 9 h 58m  NaN  
26  2023-07-26 05:14:33   0 d 1 h 57m  NaN  
27  2023-07-26 06:12:26    0 d 0 h 9m  NaN

In [225]:
df[df['d'] == 'Rachel Prassanna']['g'] # find name rachel in d colummn with g column 

2     Rachel Prassanna
6     Rachel Prassanna
7                  NaN
10                 NaN
11                 NaN
14                 NaN
21                 NaN
24                 NaN
26     Prakash Hannure
27    Rachel Prassanna
Name: g, dtype: object

In [239]:
df[df['b'] == 'TSK101489766']

Empty DataFrame
Columns: [Myshift, a, b, c, d, e, e, f, g, i, j, k]
Index: []

In [241]:
df[df['b'].str.contains('TSK101489766', case = False)] 

Myshift   a                  b              c                d         e  \
5       5 NaN  TSK101489766       chaitanya mam  Priyanka  Gadde  Activity   

                                        e                                 f  \
5  regarding the wrongly assigned tickets  CLOUD4C SERVICES PRIVATE LIMITED   

     g                    i             j    k  
5  NaN  2023-07-13 16:39:10  4 d 18 h 31m  NaN

In [1]:
a = (1,2,[3,4,5])

In [3]:
print(a)

(1, 2, [3, 4, 5])


In [31]:
print(a[2]) 

[3, 4, 5]


In [41]:
a[2].insert(2,5)

In [43]:
a

(1, 2, [3, 4, 5, 5, 5, 5])

In [47]:
a[2].remove(5)

In [49]:
a

(1, 2, [3, 4, 5, 5, 5])

In [51]:
id(a)

1402362071744

In [145]:
import copy
a = [1,2,3,4,5,6]

In [141]:
b = a

In [147]:
c = copy.deepcopy(a)

In [149]:
a

[1, 2, 3, 4, 5, 6]

In [151]:
b

[1, 2, 3, 4, 5, 6]

In [153]:
c.append(555)

In [155]:
c

[1, 2, 3, 4, 5, 6, 555]

In [157]:
a

[1, 2, 3, 4, 5, 6]

In [159]:
id(a)

1402417762880

In [161]:
id(c)

1402417778752

In [169]:
import threading
import time

In [171]:
def print_numbers():
    for i in range(5):
        print(f"print number:{i}")
        time.sleep(1)
def print_letters():
    for letters in 'abcd':
        print(f"print Letter:{lettter}")
        time.sleep(1)

thread_1 = threading.Thread(target=print_numbers)
thread_2 = threading.Thread(target=print_letters)

thread_1.start()
thread_2.start()

# Wait for threads to complete
thread_1.join()
thread_2.join()

print("Both threads have finished.")

Exception in thread Thread-10 (print_letters):
Traceback (most recent call last):
  File "C:\Users\Hi\anaconda3\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Hi\anaconda3\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Hi\AppData\Local\Temp\ipykernel_16560\3089292314.py", line 7, in print_letters
NameError: name 'lettter' is not defined. Did you mean: 'letters'?


print number:0
print number:1
print number:2
print number:3
print number:4
Both threads have finished.


In [174]:
# if model is overfit in liner regression then we are using the ridge and laso Regression 
# if model is overfit or underfit then we are using the pre puring and post pruning 
# by using adjusted r2 we are finding out the accuracy of our model 

In [178]:
# Sample Series
import pandas as pd
s = pd.Series(['cat', 'dog', 'rabbit'])

# Mapping dictionary
mapping = {'cat': 'kitten', 'dog': 'puppy', 'rabbit': 'bunny'}

# Apply map
s_mapped = s.map(mapping)

print(s_mapped)

0    kitten
1     puppy
2     bunny
dtype: object
